services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_USER: java
      MYSQL_PASSWORD: javaprojeto
    ports:
      - "3306-3306"
    expose:
      - "3306"
    volumes:
      - "./data:/var/lib/mysql"
